---
deployment:
  tasks:
    # Create necessary directories
    - export DEPLOYPATH=/home/atticusf/public_html
    - mkdir -p $DEPLOYPATH
    
    # Copy application files (excluding unnecessary files)
    - /bin/cp -R accounts $DEPLOYPATH
    - /bin/cp -R app $DEPLOYPATH
    - /bin/cp -R coonva $DEPLOYPATH
    - /bin/cp -R static $DEPLOYPATH
    - /bin/cp -R templates $DEPLOYPATH
    - /bin/cp manage.py $DEPLOYPATH
    - /bin/cp requirements.txt $DEPLOYPATH
    
    # Create media directory with proper permissions
    - mkdir -p $DEPLOYPATH/media/pfps
    - chmod 755 $DEPLOYPATH/media
    - chmod 755 $DEPLOYPATH/media/pfps
    
    # Install Python dependencies
    # Note: You'll need to use cPanel's Python environment
    # The exact path may vary - check your cPanel Python selector
    - /usr/bin/python3 -m pip install --user -r $DEPLOYPATH/requirements.txt
    
    # Create staticfiles directory
    - mkdir -p $DEPLOYPATH/staticfiles
    
    # Collect static files
    - cd $DEPLOYPATH && /usr/bin/python3 manage.py collectstatic --noinput
    
    # Run migrations
    - cd $DEPLOYPATH && /usr/bin/python3 manage.py migrate --noinput