# Generated by Django 5.2.8 on 2025-12-23 05:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('author', models.CharField(default='admin', max_length=100)),
                ('student_count', models.IntegerField(default=0)),
                ('students', models.ManyToManyField(blank=True, related_name='classes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
