# Generated by Django 5.2.8 on 2025-12-23 18:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_class_options_class_students'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='teacher',
        ),
        migrations.AddField(
            model_name='class',
            name='teachers',
            field=models.ManyToManyField(blank=True, limit_choices_to={'type': 'TEACHER'}, related_name='teaching', to=settings.AUTH_USER_MODEL),
        ),
    ]
