# Generated by Django 5.2.8 on 2025-12-23 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_class_teacher_class_teachers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='student_count',
        ),
    ]
