# Generated by Django 5.2.8 on 2025-12-24 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_class_student_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255)),
                ('due_at', models.DateTimeField()),
                ('locks_at', models.DateTimeField()),
                ('details', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='class',
            name='assignments',
            field=models.ForeignKey(blank=True, default=True, on_delete=django.db.models.deletion.CASCADE, to='app.assignment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assignment',
            name='submissions',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app.submission'),
        ),
    ]
