# Generated by Django 5.2.8 on 2025-12-24 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_assignment_submission_class_assignments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='submissions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.submission'),
        ),
        migrations.AlterField(
            model_name='class',
            name='assignments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.assignment'),
        ),
    ]
