# Generated by Django 5.2.8 on 2025-12-27 06:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_submission_student'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='submissions',
        ),
        migrations.AddField(
            model_name='submission',
            name='assignment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='assignmentSubmission', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
