# Generated by Django 5.2.8 on 2025-12-27 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_rename_name_class_title_alter_assignment_created_on_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='assignments',
        ),
        migrations.AddField(
            model_name='class',
            name='assignments',
            field=models.ManyToManyField(blank=True, null=True, related_name='Class', to='app.assignment'),
        ),
    ]
