# Generated by Django 5.2.8 on 2025-12-27 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_class_assignments_class_assignments'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='type',
            field=models.CharField(choices=[('URL', 'Url submission'), ('FILE', 'File submission'), ('TEXT', 'Text submission')], default='URL', max_length=25),
        ),
    ]
