# Generated by Django 5.2.8 on 2025-12-30 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_assignment_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='details',
        ),
        migrations.AddField(
            model_name='submission',
            name='URL',
            field=models.CharField(blank=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='details',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submission',
            name='file',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='submission',
            name='text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='class',
            name='assignments',
            field=models.ManyToManyField(blank=True, related_name='Class', to='app.assignment'),
        ),
    ]
