# Generated by Django 5.2.8 on 2025-12-30 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_remove_assignment_details_submission_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='details',
        ),
        migrations.AddField(
            model_name='assignment',
            name='details',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
