# Generated by Django 5.2.8 on 2025-12-30 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_remove_submission_details_assignment_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='URL',
            field=models.URLField(blank=True),
        ),
    ]
