# Generated by Django 5.2.8 on 2025-12-30 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_submission_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='URL',
            field=models.URLField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='submission',
            name='file',
            field=models.FileField(blank=True, default=None, upload_to=''),
        ),
        migrations.AlterField(
            model_name='submission',
            name='text',
            field=models.TextField(blank=True, default=None),
        ),
    ]
