# Generated by Django 5.2.8 on 2026-01-04 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_submission_url_alter_submission_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='submitted',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
