# Generated by Django 5.2.8 on 2026-01-04 09:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_assignment_submitted'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='submitted',
        ),
        migrations.AddField(
            model_name='assignment',
            name='submitted',
            field=models.ManyToManyField(limit_choices_to={'type': 'STUDENT'}, related_name='submitted', to=settings.AUTH_USER_MODEL),
        ),
    ]
