# Generated by Django 5.2.8 on 2025-11-18 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(default='static/img/pfp.png', upload_to='media/pfps/'),
        ),
    ]
